# Generated by Django 3.1 on 2020-08-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, null=True)),
                ('employee_role', models.CharField(max_length=50, null=True)),
                ('employee_permanent_role', models.CharField(max_length=50, null=True)),
                ('employee_leave_amount', models.CharField(max_length=50, null=True)),
                ('employee_unauthorized_leave_amount', models.CharField(max_length=50, null=True)),
                ('employee_Warnings_amount', models.CharField(max_length=50, null=True)),
                ('employee_comendations_amount', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('email_address', models.EmailField(max_length=50, null=True)),
                ('home_address', models.CharField(max_length=200, null=True)),
                ('next_of_kin', models.CharField(max_length=50, null=True)),
                ('next_of_kin_address', models.CharField(max_length=200, null=True)),
                ('next_of_kin_phone', models.CharField(max_length=50, null=True)),
                ('training_complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('ppe_issued', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('employee_agrees_terms', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
