# Generated by Django 3.1 on 2020-08-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='Date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Leave', 'Leave'), ('Uniform', 'Uniform'), ('Saftey Concern', 'Saftey Concern')], max_length=200, null=True)),
                ('leave_from', models.DateTimeField(null=True)),
                ('leave_to', models.DateTimeField(null=True)),
                ('Uniformtype', models.CharField(choices=[('Winter Jacket', 'Winter Jacket'), ('Shell Coat', 'Shell Coat'), ('Jumper', 'Jumper'), ('T-Shirt', 'T-Shirt'), ('Trousers', 'Trousers'), ('Boots', 'Boots')], max_length=200, null=True)),
                ('Uniformsize', models.CharField(max_length=50, null=True)),
                ('Saftey_concern', models.CharField(max_length=500, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.ManyToManyField(to='accounts.tag')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.requests')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
        ),
    ]
