# Generated by Django 3.1 on 2020-08-21 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200817_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Granted', 'Granted')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Uniformtype',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Winter Jacket', 'Winter Jacket'), ('Shell Coat', 'Shell Coat'), ('Jumper', 'Jumper'), ('T-Shirt', 'T-Shirt'), ('Trousers', 'Trousers'), ('Boots', 'Boots')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_role',
            field=models.CharField(choices=[('MANAGEMENT', 'MANAGEMENT'), ('SUPERVISER', 'SUPERVISER'), ('HGV DRIVER', 'HGV DRIVER'), ('LOADER', 'LOADER'), ('STREETS DRIVER', 'STREETS DRIVER'), ('STREETS LOADER', 'STREETS LOADER')], max_length=50, null=True),
        ),
    ]
