# Generated by Django 3.1 on 2020-08-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_orders_leave_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='leave_from',
        ),
    ]
