# Generated by Django 3.1 on 2020-08-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_remove_orders_leave_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Saftey_concern',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Uniformsize',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Uniformtype',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Winter Jacket', 'Winter Jacket'), ('Shell Coat', 'Shell Coat'), ('Jumper', 'Jumper'), ('T-Shirt', 'T-Shirt'), ('Trousers', 'Trousers'), ('Boots', 'Boots')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='leave_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='leave_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_Warnings_amount',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_comendations_amount',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_leave_amount',
            field=models.CharField(default=25, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_unauthorized_leave_amount',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
