# Generated by Django 3.1 on 2020-08-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200822_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Saftey_concern',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Uniformsize',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Uniformtype',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='leave_from',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='leave_to',
        ),
        migrations.AddField(
            model_name='requests',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
    ]
