# Generated by Django 3.1 on 2020-08-22 20:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200822_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='Saftey_concern',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='Uniformsize',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='Uniformtype',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='leave_from',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='leave_to',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='staff',
        ),
        migrations.AddField(
            model_name='orders',
            name='Saftey_concern',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Uniformsize',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Uniformtype',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Winter Jacket', 'Winter Jacket'), ('Shell Coat', 'Shell Coat'), ('Jumper', 'Jumper'), ('T-Shirt', 'T-Shirt'), ('Trousers', 'Trousers'), ('Boots', 'Boots')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='leave_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='leave_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='request',
            field=models.CharField(max_length=50, null=True, verbose_name=accounts.models.requests),
        ),
    ]
