# Generated by Django 3.1 on 2020-08-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200822_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='request',
            field=models.CharField(choices=[('Leave', 'Leave'), ('Uniform', 'Uniform'), ('Saftey Concern', 'Saftey Concern')], max_length=50, null=True),
        ),
    ]
