# Generated by Django 3.1 on 2020-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200823_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Granted', 'Granted')], default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='home_address',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='next_of_kin_address',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
